### PR TITLE
Feature chg

### PR DESCRIPTION
**Pull request by Grisly00**
Make limit method of PointCloud accept None values

### CODE REVIEW

**Comment by tgoelles** [comment]
This PR contains also the changes from the other PR #45 . It should only contain the new changes separate from #45 . 

Why do you need the default value of None in the limit method?
Also I think it should then throw a ValueError exception and not just a print.

**Comment by Grisly00** [comment]
Will make a separate PR next time.

Sometimes I want to apply only a max or only a min limit and not both. With the current implementation I would need to do something like this for applying a max limit of 15 only:
`pc.limit("x", -999, 15)`
which i find not clean.

To not raise an error when both are None could makes integration in a framework more easy, but this is debatable I guess.
Maybe raise a warning instead of a print?

**Comment by tgoelles** [comment]
ok, thats what filter is for.

limit is actually just using 2 filters. One for max and one for min.

self.filter("value", dim, ">=", minvalue).filter( "value", dim, "<=", maxvalue)

so in your example:

pc.filter("value", "x","<=", 15)

Therfore, I just want to keep the current implementation of limit.

**Comment by Grisly00** [comment]
Yes, I know. I just find it less intuitive. But, your call, of course.

**Comment by tgoelles** [comment]
Ok, your suggestion

pc.limit("x",5) 

could then actual mean lower or upper limit which is dangerous and unclear.

But maybe the default for the filter to "value" would be good in this case like.

pc.filter("x","<=",5) is the same as pc.filter("value", x","<=",5).

Would this be more intuitive?

**Comment by Grisly00** [comment]
I see your point. Maybe remove the default values in the limit method, but keep the None handling?
In that way one has to be explicit like before, but could use it with Nones.
Otherwise, I would just keep it as is.

**Comment by tgoelles** [comment]
solved in PR #54 

now: limit_less and limit_greater

**Pull request closed without merging**
